//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int id { get; set; }
        public Nullable<int> клиент_id { get; set; }
        public Nullable<int> офисы_id { get; set; }
        public Nullable<int> условия_выпуска_id { get; set; }
        public Nullable<int> дизайн_id { get; set; }
        public Nullable<int> тариф_id { get; set; }
    
        public virtual дизайн дизайн { get; set; }
        public virtual офисы офисы { get; set; }
        public virtual условия_выпуска условия_выпуска { get; set; }
        public virtual клиент клиент { get; set; }
        public virtual тариф тариф { get; set; }
    }
}
