//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class ЗаказчикПартнер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ЗаказчикПартнер()
        {
            this.История = new HashSet<История>();
        }
    
        public int ID_ЗаказчикаПартнера { get; set; }
        public string Наименование { get; set; }
        public string Информация { get; set; }
        public int ID_Истории { get; set; }
        public int ID_СтатусаЗП { get; set; }
    
        public virtual СтатусЗаказчикаПартнера СтатусЗаказчикаПартнера { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История> История { get; set; }
    }
}
