//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИнфоРазработки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ИнфоРазработки()
        {
            this.Проекты = new HashSet<Проекты>();
        }
    
        public int ID_ИнфоРазработки { get; set; }
        public int ID_СтатусаРазработки { get; set; }
        public System.DateTime ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаЗавершения { get; set; }
        public int ID_КомандыРазработчиков { get; set; }
        public int Бюджет { get; set; }
    
        public virtual КомандаРазработчиков КомандаРазработчиков { get; set; }
        public virtual СтатусРазработки СтатусРазработки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Проекты> Проекты { get; set; }
    }
}
