//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class карты
    {
        public int id { get; set; }
        public string номер_карты { get; set; }
        public Nullable<System.DateTime> срок_действия { get; set; }
        public string имя_на_карте { get; set; }
        public Nullable<int> тариф_id { get; set; }
        public Nullable<int> дизайн_id { get; set; }
        public Nullable<int> статус_карты_id { get; set; }
        public string номер_счета { get; set; }
    
        public virtual дизайн дизайн { get; set; }
        public virtual статус_карты статус_карты { get; set; }
        public virtual тариф тариф { get; set; }
        public virtual счета счета { get; set; }
    }
}
