//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Компания
    {
        public int ID_Компании { get; set; }
        public string Название { get; set; }
        public string Владелец { get; set; }
        public string Сайт { get; set; }
        public string Почта { get; set; }
        public string Телефон { get; set; }
        public string ИнформацияОКомпании { get; set; }
        public System.DateTime ДатаОснования { get; set; }
    }
}
