//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Обновления
    {
        public int ID_Обновления { get; set; }
        public int ID_Проекта { get; set; }
        public System.DateTime ДатаОбновления { get; set; }
        public int КодОбновления { get; set; }
        public string СписокИзменений { get; set; }
        public Nullable<int> ОценкаОбновления { get; set; }
    
        public virtual Проекты Проекты { get; set; }
    }
}
