//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Проекты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Проекты()
        {
            this.Обновления = new HashSet<Обновления>();
            this.РезультатыТестирования = new HashSet<РезультатыТестирования>();
        }
    
        public int ID_Проекта { get; set; }
        public string НазваниеПроекта { get; set; }
        public System.DateTime ДатаВыпуска { get; set; }
        public int ID_Жанра { get; set; }
        public string Описание { get; set; }
        public int ID_ИнфоРазработки { get; set; }
    
        public virtual Жанр Жанр { get; set; }
        public virtual ИнфоРазработки ИнфоРазработки { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Обновления> Обновления { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РезультатыТестирования> РезультатыТестирования { get; set; }
    }
}
