//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class РезультатыТестирования
    {
        public int ID_Тестирования { get; set; }
        public int ID_Проекта { get; set; }
        public System.DateTime ДатаТестирования { get; set; }
        public string Цель { get; set; }
        public string Отчет { get; set; }
    
        public virtual Проекты Проекты { get; set; }
    }
}
