//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace курсовая
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотруудник
    {
        public int ID_Сотрудника { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public int ID_Должности { get; set; }
        public int ID_КомандыРазработчиков { get; set; }
        public string Телефон { get; set; }
        public string Почта { get; set; }
        public System.DateTime ДатаПриема { get; set; }
        public Nullable<System.DateTime> ДатаУвольнения { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual КомандаРазработчиков КомандаРазработчиков { get; set; }
    }
}
